#index:
#    path: /
#    controller: App\Controller\DefaultController::index
users_login:
    path: /login
    controller: App\Controller\UsersController::login
rates_new:
    path: /rates/new
    controller: App\Controller\RatesController::new
